[package]
name = "exa"
version = "0.2.0"
edition = "2018"

[dependencies]
unicode-segmentation = "1.8.0"
crossterm = "0.21"
toml = "0.5.8"
dirs = "3.0.2"
anyhow = "1.0.43"
colors-transform = "0.2.11"
